version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: app_mysql
    volumes:
      - ../mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
   
  webapp:
    build: ../app
    container_name: app_web
    links:
        - mysql
    depends_on:
        - mysql
    ports:
        - "8888:8888"
